export const NAMES = [
    "adnw-english-bigram",
    "aptv3",
    "arensito",
    "arts",
    "asset",
    "balance-12",
    "beakl-15",
    "beakl-19",
    "beakl-19-bis",
    "blaze",
    "boo",
    "canary",
    "capewell",
    "capewell-dvorak",
    "colemak",
    "colemak-dh",
    "colemak-dhv",
    "colemak-pine",
    "colemak-qi",
    "colemak-qi;x",
    "colemaq",
    "colemaq-f",
    "colman",
    "crest",
    "ctgap",
    "dhorf",
    "dvarf",
    "dvorak",
    "dvormax",
    "dwarf",
    "engram",
    "ev29",
    "fire",
    "flame",
    "flaw",
    "flow",
    "gallium",
    "gemini",
    "graphite",
    "halmak",
    "hands-down",
    "hands-down-neu",
    "hands-right",
    "hands-up",
    "heart",
    "hieamtsrn",
    "hyperroll",
    "ints",
    "isrt",
    "kaehi",
    "klauser",
    "lela",
    "maya",
    "megamak",
    "minimak-12",
    "mtgap",
    "nerps",
    "nerts",
    "nila",
    "niro",
    "nitrogen",
    "noctum",
    "norman",
    "nrstmak",
    "nstr",
    "octa8",
    "oneproduct",
    "phonkie",
    "pine",
    "poqtea",
    "poutea",
    "qgmlwy",
    "qwerf",
    "qwerty",
    "qwpr",
    "real",
    "rhea",
    "rolll",
    "rollla",
    "rollly",
    "rollly2",
    "rollmak",
    "rsi-terminated",
    "rtna",
    "seht-drai",
    "semimak",
    "semimak-jq",
    "sertain",
    "sind",
    "snug",
    "soul",
    "stndc",
    "sturdy",
    "synth",
    "tesc",
    "trendei",
    "trendy",
    "typehack",
    "uciea",
    "urts",
    "whorf",
    "workman",
    "wreath",
    "wreathy"
]

export const LAYOUTS = {
    "minimak-12": "qwdfkyuil;astrghneopzxcvbjm,./",
    "flame": "xpdwgjfou,rntsyqlaeizbkcvmh';.",
    "colemak-pine": "qlcgkjfuy/arstdbneiozxwmvph',.",
    "colemak-qi": "qlwmkjfuy'arstgpneiozxcdvbh,./",
    "megamak": "xlywkzfou;crstgbneiajvdmqph/,.",
    "beakl-19-bis": "qyouzwdnckhiea,gtrspj'/.xvmlfb",
    "dvorak": "',.pyfgcrlaoeuidhtns;qjkxbmwvz",
    "capewell-dvorak": "',.pyqfgrkoaeiudhtnszxcvjlmwb;",
    "hands-right": "vlcdkz'uoynrstgpheaiqxwmjbf,.;",
    "arts": "qldgvjfuy'artswpneiozxmcbkh;,.",
    "seht-drai": "fulvb;gnojsehtkqdraiz'mpwycx.,",
    "rollly": "youfjqmwl,iaenbktsrc/\"hpzvdgx.",
    "rtna": "xdh.qbfoujrtna;gweislkm,'pczyv",
    "maya": "bldgqjfou,nrtsvkhaeixmcwzpy'/.",
    "qwerty": "qwertyuiopasdfghjkl;zxcvbnm,./",
    "wreath": "jgdfbqluoynsthkwreaixcmpvz,.'/",
    "asset": "qwjfgypul;asetdhniorzxcvbkm,./",
    "phonkie": "qlmpbzfuoyrnthdcseaijxvk;wg'.,",
    "mtgap": "ypoujkdlcwinea,mhtsr;?'.-bfgvq",
    "noctum": "bcdmzjfou,nstrvyhaeiqwglxkp';.",
    "blaze": "wpdgvqxoujrntsf.haeibkcyzml';,",
    "gemini": "xlmgwqfou,srtdybnaeivjkczph';.",
    "hands-down-neu": "wfmpv/.q\"'rsntb,aeihxcldg-uoyk",
    "beakl-19": "q.oujwdnm,haeikgsrtpz'/yxbclfv",
    "sturdy": "vmlcpxfoujstrdy.naeizkqgwbh';,",
    "nrstmak": "qwypbjkou,nrstdlhaeizxcfgvm';.",
    "hieamtsrn": "byou'kdclphiea,mtsrnx().?wgfjz",
    "kaehi": "qwldgjuop/nrstmkaehizxcvbyf,.;",
    "semimak": "flhvzqwuoysrntkcdeaix'bmjpg,./",
    "sertain": "xldkvzwou;srtnfgyeiaqjmhbpc',.",
    "ctgap": "qplcjxfou/rntsgyheiazbmwvkd',.",
    "real": "yluo.zfhcwirea,dtnsm;j'qxpkbgv",
    "trendy": "klhwzjfou,trndcysaeiqxmpbgv.';",
    "uciea": "pyuo-kdhfxciea'gtnsrz\",.;wmlbj",
    "wreathy": "qgdfvjluo,nsthywreaibcmpkzx/'.",
    "klauser": "k,uypwlmfcoaeidrnthsq.';zxvgbj",
    "poqtea": "ywflmkpoq-ursnhdteaizxcvjbg,.;",
    "gallium": "bldcvzyou,nrtsgfhaeiqxmwjkp';.",
    "sind": "y,hwfqkouxsindcvtaerj.lpbgm'/z",
    "lela": "ylwkjzfou.crstvbnaeixmgdqph'/,",
    "colemaq-f": ";wgpbjluyqarstfmneiozxcdkvh/.,",
    "colemak-dh": "qwfpbjluy;arstgmneiozxcdvkh,./",
    "synth": "wlgfk/quoycsthbxreaijvmdpzn',.",
    "snug": "qldmbyfou'srtcgpneiazxkwvjh/,.",
    "hands-up": "fyou,kwclphiea.dtsrnbj'z;vmgxq",
    "balance-12": "plcdw'uoyknrstm,aeihzjfgb?.()x",
    "flaw": "flawpzkur/hsoycmtenibj'gvqd.x,",
    "colemak-dhv": "qwcpbjluy;arstgmneiozxfdkvh/.,",
    "oneproduct": "pldwgjxoyqnrstmuaeihzcfvb,.';k",
    "crest": "wlfdkzjuoycrstgpneai'xvmqbh,.;",
    "colman": "qlrwbjmuy;anhsfpteiozxvckgd,./",
    "ints": "foumjqgdp,haerxvstni'/lwzyckb.",
    "nerts": "pldvxzkou;nrtsgyheiaqjmcwbf',.",
    "colemak": "qwfpgjluy;arstdhneiozxcvbkm,./",
    "arensito": "ql.p';fudkarenbgsitozw,hjvcymx",
    "rsi-terminated": "zcywkxlu,qrsitgmneaojfpdbvh'.?",
    "flow": "vphmzjfou;snrtxyceiabldkqgw',.",
    "aptv3": "wgdfbqluoyrsthkjneaixcmpvz,.'/",
    "graphite": "bldwz'foujnrtsgyhaeiqxmcvkp.-/",
    "fire": "pldgvzfou;nrtsyjheiaxkcwqbm',.",
    "rolll": "youwbxkclviaenpdhsrtj/,.qfmg'z",
    "rollly2": "youlqkmwp,iaerxgtsnc/\"hjzvdfb.",
    "colemaq": ";wfpbjluyqarstgmneiozxcdkvh/.,",
    "nitrogen": "pmlcwfdou,ntrsgyhaeizqjbvxk';.",
    "nila": "xdlcvqfou,rtnsbyhaeikmgwzjp'/.",
    "qwerf": "qwerfjylk;asdtghuiopzxcvbnm,./",
    "niro": "qwudpjfyl;asetghnirozxcvbkm,./",
    "engram": "byou'\"ldwvciea,.htsngxjk-?rmfp",
    "nerps": "xldpvzkou;nrtsgyheiaqjmcwbf',.",
    "hands-down": "qchpvkyoj/rsntgwueiaxmldbzf',.",
    "rollmak": "qwfpbzluo;crstgmneaivxydkjh/,.",
    "boo": ",.ucvqfdlyaoesgbntri;x'wzphmkj",
    "hyperroll": "pclmvxuoyfnsrtd.aeihbg'wz/,qjk",
    "canary": "wlypkzxou;crstbfneiajvdgqmh/,.",
    "colemak-qi;x": ";lcmkjfuyqarstgpneiozxwdvbh/.,",
    "ev29": "y,ofbjvrkmiaehpgsnut;.'dzwclxq",
    "adnw-english-bigram": "qyu.?zmldbsieaohnrtcj)',(fxwkv",
    "semimak-jq": "flhvz'wuoysrntkcdeaixjbmqpg,./",
    "capewell": ".ywdfjpluqaersgbtnioxzcv;kmh,'",
    "tesc": "krngvjpuo/tlhsfyciaeqzbmxwd,.;",
    "halmak": "wlrbz;qudjshnt,.aeoifmvc/gpxky",
    "heart": "qcdvkjyou;rsthlpnaiewgbmxzf,./",
    "norman": "qwdfkjurl;asetgyniohzxcvbpm,./",
    "workman": "qdrwbjfup;ashtgyneoizxmcvkl,./",
    "beakl-15": "qhouxgcrfzyiea.dstnbj/,k'wmlpv",
    "stndc": "vmhgpxlouystndcwraeizkbfq,.'\"?",
    "rollla": "youb.xkclviaen,mhsrt'/pwzfdgjq",
    "nstr": "vgdlqzuoybnstrk,aeihpcmwx;./jf",
    "qwpr": "qwprfyukl;asdtghnioezxcvbjm,./",
    "typehack": "jghpfqvou;rsntkyiaelzwmdbc,'.x",
    "pine": "ylrmkqfou,csntgbhaeijxzwvpd'/.",
    "soul": "qwldpkmuy;asrtgfneiozxcvjbh,./",
    "whorf": "flhdmvwou,srntkgyaeixjbzqpc';.",
    "octa8": "youkxgwdl,iaenfbstrcq/zh'vpmj.",
    "dhorf": "vlhgqjfou,srntbycaeizxmdkpw';.",
    "dvarf": "'uowpqvdrfaieyglhtns,.;cjkmbxz",
    "isrt": "yclmkzfu,'isrtgpneaoqvwdjbh/.x",
    "urts": "vldcfqbo,yurtsgjneaikxmwzph'.;",
    "dwarf": "flhdvzgou.srntmpyeiaxjbkqcw',;",
    "rhea": "vblpfqxuoystndc.reaikmgwz,h';j",
    "qgmlwy": "qgmlwyfub;dstnriaeohzxcvjkp,./",
    "dvormax": "kyu.?zlmdprieaohnstcx)',(jqfgb",
    "poutea": "kjflmbpou-yrsnhdteaizxcvqwg,.;",
    "trendei": "klhwbzfou;trndcyseiajmgpqxv',."
}