export const NAMES = [
    "adnw-english-bigram",
    "aptv3",
    "arensito",
    "arts",
    "asset",
    "balance-12",
    "beakl-15",
    "beakl-19",
    "beakl-19-bis",
    "blaze",
    "boo",
    "canary",
    "capewell",
    "capewell-dvorak",
    "colemak",
    "colemak-dh",
    "colemak-dhv",
    "colemak-pine",
    "colemak-qi",
    "colemak-qi;x",
    "colemaq",
    "colemaq-f",
    "colman",
    "crest",
    "ctgap",
    "dhorf",
    "dvarf",
    "dvorak",
    "dvormax",
    "dwarf",
    "engram",
    "ev29",
    "fire",
    "flame",
    "flaw",
    "flow",
    "gallium",
    "gemini",
    "graphite",
    "halmak",
    "hands-down",
    "hands-down-neu",
    "hands-right",
    "hands-up",
    "heart",
    "hieamtsrn",
    "hyperroll",
    "ints",
    "isrt",
    "kaehi",
    "klauser",
    "lela",
    "maya",
    "megamak",
    "minimak-12",
    "mtgap",
    "nerps",
    "nerts",
    "nila",
    "niro",
    "nitrogen",
    "noctum",
    "norman",
    "nrstmak",
    "nstr",
    "octa8",
    "oneproduct",
    "phonkie",
    "pine",
    "poqtea",
    "poutea",
    "qgmlwy",
    "qwerf",
    "qwerty",
    "qwpr",
    "real",
    "rhea",
    "rolll",
    "rollla",
    "rollly",
    "rollly2",
    "rollmak",
    "rsi-terminated",
    "rtna",
    "seht-drai",
    "semimak",
    "semimak-jq",
    "sertain",
    "sind",
    "snug",
    "soul",
    "stndc",
    "sturdy",
    "synth",
    "tesc",
    "trendei",
    "trendy",
    "typehack",
    "uciea",
    "urts",
    "whorf",
    "workman",
    "wreath",
    "wreathy"
]

export const LAYOUTS = {
    "io": ",.putslg';xwmnohadbqzvfyeircjk",
    "odu": "xlhfwqodujsrncg.ateivzmpb',k;y",
    "cmk": "ypoujkdlcwinea,mhtsrqz'.;bfgvx",
    "ntr": "bdlvfqaujzntrgc'oeispkhwm;.,yx",
    "apt": "wgdfbqluoyrsthkjneaixcmpvz,.'/",
    "idk": "blcmkz';,.nrstwjaeihpxgdvquoyf",
    "sur": "'x,bq.fm/ziratgpcnesylodkjwhuv",
    "uwu": "eu'wcsnjvaob/fkhgq.ptyxmlirz,d",
    "boo": ",.ucvqfdlyaoesgbntri;x'wzphmkj",
    "apty": "jgdlqzyou'rsthkpneiaxcbmvwf,./",
    "lrst": "qwcpkjyou'lrstgmneiaxvfdbzh,./",
    "rrll": "xchpbqyou'rsntgjiaelwfmdv/z,.k",
    "ev21": "vxhgkjwou,rsntmpyeiazbldqfc'.;",
    "ouae": "xplmvqoudjsnrcg'aetizbhfw;.,ky",
    "ev12": "wcldgxuoy.rsntpfheiaqzmbv,k'j/",
    "dvim": "zmldf,uoy'rntsgpaeihxbwcv/kj.q",
    "hrst": "flwkvzbuoyhrstd.neai'xcmgp,/qj",
    "nore": "qmluwkdypjnorebhaitszxgv'fc,./",
    "ev20": "vyldkxbou/rcntmfseiazphgqjw',.",
    "ev23": "wcldgxuoy.rsntbfheiaqzmpv,k'j;",
    "saaz": "/vwmkzfuxqasrtgpneoi.cldjbh',y",
    "iron": "klhbvzcou'trnsmpdaieqxjgfwy,.;",
    "cumy": "nlcumy'vhrdgqfbj;zwsiakpo.,xte",
    "ev24": "hkldgjwo,yruntbfseaiqvmpzxc'./",
    "ev19": "wclpvxfou,rsntgyheiajzmbqkd'.;",
    "apos": "jclmkzfouqisrtgpnae'ywxdvbh,./",
    "nstd": "bfmcpzlou,nstdyjraeiqvkgwxh';.",
    "ev22": "wplcfqyou-rdtsgxneiajkmbvzh',.",
    "oooo": "wclfkzvou.rsthyxneiajgmdpqb',;",
    "ev13": "ywouzkdlfvisea,ptncrjx'.;bghmq",
    "zwou": "pldfkzwou,nrthyvsaeiqjmcgxb';.",
    "aest": ".,;irhwgpq'ayesntmvjxoubldcfkz",
    "inar": "ypolzqmufginarxktesc;b.hjvd,w'",
    "aptx": "qcdwxzpou;rstnvyheialgbmjkf',.",
    "khlc": "khlcv.ybj'tsrnduaieoqzwm;gfp,x",
    "zyou": "vlhfwzyou,srncgktaeixjmpbqd';.",
    "ev17": "yfouzqmrxwihea.gtnscjk',;vdlbp",
    "ev27": ",uoyfjgrblaiehkdtncs;.'pqxmwvz",
    "lore": "bcgu.jmopqndsiylretazwfx,vh;k'",
    "vlbu": "vlbuaoygdrz;xk',.cqneiwmsjfpht",
    "ev26": "wbldfjyou,rstcgkneiaqxmpvzh'.?",
    "ants": "xpmdf.roy,antsgqheiu/bwcz;ljkv",
    "arts": "qldgvjfuy'artswpneiozxmcbkh;,.",
    "rtna": "xdh.qbfoujrtna;gweislkm,'pczyv",
    "maya": "bldgqjfou,nrtsvkhaeixmcwzpy'/.",
    "real": "yluo.zfhcwirea,dtnsm;j'qxpkbgv",
    "sind": "y,hwfqkouxsindcvtaerj.lpbgm'/z",
    "lela": "ylwkjzfou.crstvbnaeixmgdqph'/,",
    "snug": "qldmbyfou'srtcgpneiazxkwvjh/,.",
    "flaw": "flawpzkur/hsoycmtenibj'gvqd.x,",
    "ints": "foumjqgdp,haerxvstni'/lwzyckb.",
    "flow": "vphmzjfou;snrtxyceiabldkqgw',.",
    "fire": "pldgvzfou;nrtsyjheiaxkcwqbm',.",
    "nila": "xdlcvqfou,rtnsbyhaeikmgwzjp'/.",
    "niro": "qwudpjfyl;asetghnirozxcvbkm,./",
    "ev29": "y,ofbjvrkmiaehpgsnut;.'dzwclxq",
    "tesc": "krngvjpuo/tlhsfyciaeqzbmxwd,.;",
    "nstr": "vgdlqzuoybnstrk,aeihpcmwx;./jf",
    "qwpr": "qwprfyukl;asdtghnioezxcvbjm,./",
    "pine": "ylrmkqfou,csntgbhaeijxzwvpd'/.",
    "soul": "qwldpkmuy;asrtgfneiozxcvjbh,./",
    "isrt": "yclmkzfu,'isrtgpneaoqvwdjbh/.x",
    "urts": "vldcfqbo,yurtsgjneaikxmwzph'.;",
    "rhea": "vblpfqxuoystndc.reaikmgwz,h';j",
    "short": "juofwkbnlzeiacydtrhs;,.g'vpqmx",
    "ursnf": "klcmbqpaj.ursnfgtoiewxyhvzd',;",
    "skrrt": "vyldgqfoujscrtkbnaeixw'mzph.;,",
    "strd1": "vmlcpqzuo,strdyfneaixkjgwbh;'.",
    "wharf": ".uocfqknl,ieaygvthrs;'wpzmdbjx",
    "iaern": ",ouqjkbmcxiaernhdtys.;'lzpfgwv",
    "fnerb": "twgsbqlnayrhjkdupeoixfmzcv',./",
    "siuol": "xclgkqjuoyrsthdbneai'wvmzpf.,;",
    "iron2": "klcmvzjou'trshypnaieqxgdfbw.,;",
    "radon": "frlgkqyou'snhtbcdaiezxmpvjw,.;",
    "three": "qfuyzxkcwboheaidrtns,m.j;glpv'",
    "temma": "zxmbq.fou'srntgpcaeivlhdkjw,/y",
    "tahan": "tahzyxuiopqvgrsnkblwmfecdj';/-",
    "nitro": "pmlcvxfou.ntrsybhaeiqzjgwkd';,",
    "snort": "xplkq'woujsnrtmycaeizbhdvgf.;,",
    "crstm": "wlgdvbhuoycrstmfneai'jxkqzp/,.",
    "aujus": ".oujpvglbziaetwyshnr,/;dkfcmxq",
    "apt30": "vgdfbwluoyrsthkjneaixcmpqz,.'/",
    "learn": ",ourjkpmcxiaenldhtys.;'qzbfgwv",
    "aptv4": "wgdlvjyou'rsthkpneiaxcbmqzf,./",
    "runts": "xpdwgqfou,rntsyjlaeizbkcvmh';.",
    "straw": "xcdmqjyou,nstrwphaeizbglvkf';.",
    "ocmak": ",wfpbxvuy'arstgmneiozcdkqlhj./",
    "apthd": "wfypbqlou'rsthkjneiaxcgdvzm/,.",
    "trash": "vlocx'fpuytrasgkdneiqj.wzhmb,/",
    "flame": "xpdwgjfou,rntsyqlaeizbkcvmh';.",
    "asset": "qwjfgypul;asetdhniorzxcvbkm,./",
    "mtgap": "ypoujkdlcwinea,mhtsr;?'.-bfgvq",
    "blaze": "wpdgvqxoujrntsf.haeibkcyzml';,",
    "kaehi": "qwldgjuop/nrstmkaehizxcvbyf,.;",
    "ctgap": "qplcjxfou/rntsgyheiazbmwvkd',.",
    "uciea": "pyuo-kdhfxciea'gtnsrz\",.;wmlbj",
    "synth": "wlgfk/quoycsthbxreaijvmdpzn',.",
    "crest": "wlfdkzjuoycrstgpneai'xvmqbh,.;",
    "nerts": "pldvxzkou;nrtsgyheiaqjmcwbf',.",
    "aptv3": "wgdfbqluoyrsthkjneaixcmpvz,.'/",
    "rolll": "youwbxkclviaenpdhsrtj/,.qfmg'z",
    "qwerf": "qwerfjylk;asdtghuiopzxcvbnm,./",
    "nerps": "xldpvzkou;nrtsgyheiaqjmcwbf',.",
    "heart": "qcdvkjyou;rsthlpnaiewgbmxzf,./",
    "stndc": "vmhgpxlouystndcwraeizkbfq,.'\"?",
    "whorf": "flhdmvwou,srntkgyaeixjbzqpc';.",
    "octa8": "youkxgwdl,iaenfbstrcq/zh'vpmj.",
    "dhorf": "vlhgqjfou,srntbycaeizxmdkpw';.",
    "dvarf": "'uowpqvdrfaieyglhtns,.;cjkmbxz",
    "dwarf": "flhdvzgou.srntmpyeiaxjbkqcw',;",
    "dofauq": ".auqmvgphxioetdysnlr,/;wkfcbjz",
    "qwertz": "qwertzuiopasdfghjkl;yxcvbnm,./",
    "wogcat": "xie'.zvlybwogcatdrsnu;j,qmkhfp",
    "awertz": "awertzuiopqsdfghjklmyxcvbn,./;",
    "rusnet": "jylmqwfou.rsntkbceiazxhdvgp',;",
    "spruce": "xdlcbjpou,rtnswyhaeizqmgvkf';.",
    "helium": "pldcgvuoyqnrtsbfheiajxmwzk.';,",
    "doerak": "juo'qzvrshgaiexbtndlc.,y;pmfkw",
    "jrstai": "jrstbzgmdiqwypeufca'kvlnxho/,.",
    "whorf6": "vlhkjgwou.srntmydeaixqbfzpc',;",
    "stormy": "zkhgwbfoujstrmy,naeixdlcvqp';.",
    "radish": "vcwfqzpuoyrdshlkteaixjmn;bg',.",
    "dofgun": "ltaxz'weh.rdofvygunijkqmspc;b,",
    "aptsym": "wcdl,.youqrsthkpneiavbgm'/fjxz",
    "zyvern": "xdlwvqpuoyrthscbneai/kmgjzf'.,",
    "dvimak": "zwmgxpduoynrtscfheai/lkjvqb,.;",
    "querty": "quertywiopasdfghjkl;zxcvbnm,./",
    "crstm2": "pwfmbjluoycrstkxneai'vgdqzh/,.",
    "qwetry": "qwetryuiopasdfghjkl;zxcvbnm,./",
    "iaern2": ",ouqjfpmcxiaerndhtys.;'lzbkgwv",
    "jcuken": "jcukengzh-fywaproldvq.smitxb',",
    "osmium": "tb'umdiqwnsv;f,cpx.oekjgyrlzha",
    "whorf2": "flndmvwou,srhtqgyaeijbkxzpc';.",
    "potato": "qlcgvjfou,nrstdyhaeizxwmbkp'/.",
    "tnwmlc": "tnwmlcbprhsgxjfkqzv;eadioyu,./",
    "whorse": "vphmqjfou,snrtkycaeixbldzwg';.",
    "azerty": "azertyuiopqsdfghjklmwxcvbn,./;",
    "short2": "juofwqklnvieacymtrhs,;.p'gdxbz",
    "wourst": "vlngfjbqy/urstdhieaowxmczkp',.",
    "apthd2": "qfypbjluo,rsthkwneaizcgdvxm/'.",
    "castra": "bpdlkqwuoycstr,.neaivgfh';mzxj",
    "scythe": "vcdjxqwou,sytrlfnaeizgkhmbp';.",
    "dvorak": "',.pyfgcrlaoeuidhtns;qjkxbmwvz",
    "rollly": "youfjqmwl,iaenbktsrc/\"hpzvdgx.",
    "qwerty": "qwertyuiopasdfghjkl;zxcvbnm,./",
    "wreath": "jgdfbqluoynsthkwreaixcmpvz,.'/",
    "noctum": "bcdmzjfou,nstrvyhaeiqwglxkp';.",
    "gemini": "xlmgwqfou,srtdybnaeivjkczph';.",
    "sturdy": "vmlcpxfoujstrdy.naeizkqgwbh';,",
    "trendy": "klhwzjfou,trndcysaeiqxmpbgv.';",
    "poqtea": "ywflmkpoq-ursnhdteaizxcvjbg,.;",
    "colman": "qlrwbjmuy;anhsfpteiozxvckgd,./",
    "engram": "byou'\"ldwvciea,.htsngxjk-?rmfp",
    "canary": "wlypkzxou;crstbfneiajvdgqmh/,.",
    "halmak": "wlrbz;qudjshnt,.aeoifmvc/gpxky",
    "norman": "qwdfkjurl;asetgyniohzxcvbpm,./",
    "rollla": "youb.xkclviaen,mhsrt'/pwzfdgjq",
    "qgmlwy": "qgmlwyfub;dstnriaeohzxcvjkp,./",
    "poutea": "kjflmbpou-yrsnhdteaizxcvqwg,.;",
    "flow-ao": "vphmzjfou,snrtxycaeibldkqgw';.",
    "natasha": "pmcfkj'uoyntshbwreaiqvgdxzl,.;",
    "apthd30": "vcydbxlou'rsthkwneiajfgpqzm,./",
    "dvimcat": "wpdgf,.uoyrntsbjheaixvmczkl';q",
    "foalmak": "bx,wvz/utkfoalsneighp'.mcqjydr",
    "swapsix": "qwdrfyukl;asetghniopzxcvbjm,./",
    "colevim": "zwfbp;muy.arstg,neioxvcdqlhjk/",
    "pinerev": "yrlmkqfuo,cnstgbheaijzxwvpd/'.",
    "woagium": "cdlhbpyou,strnmgwaeijkxvzqf';.",
    "stupid2": "qbdlzjfuoyrctswmneai;pkvgxh.',",
    "evtest1": "wcldbkyoj.rsntguheiaqzmpvxf',;",
    "qwertwo": "qwertyblu.asdfmpcnio'z;kjvgh,x",
    "colemap": "qwfgbjluy;arstdhneiozxcpvkm,./",
    "copemak": "qwfgvjmuy;arstdhneiozxcpbkl,./",
    "ace-vim": "jlhkgqpuo,srntmyceaizxbdvwf/;.",
    "evtest9": "wclpvxfou/rsntgyheiaqzmbjkd',.",
    "therein": "zjoukwplcmsiaedythrn.;vbxgqf?,",
    "calemog": "xlcwkzfuy;orstmbneiaqjvdgph',.",
    "stupid1": "bwdyvxro.uscthfjneaizgmpkql',/",
    "aptsym2": "qckv'/puoyrstlmbneaiwgdh,.fzxj",
    "mtgap30": "ypoujkdlcwinea,mhtsrqz'.;bfgvx",
    "nitro-s": "pmldxvcou,ntrhybsaeizqjfkwg';.",
    "pinball": "zkdvqjfou,nthrwysaeipbmlxgc';.",
    "jrstai2": "rwopbyimdasfghjkl'u,qexvctzn/.",
    "stencil": "fdhgwqluoystncbjreaizkmpvx;',.",
    "heartae": "qcdvkjyou;rsthlpneiawgbmxzf,./",
    "adept30": "jwmpqzyou'rsntgvheiaxcldbkf,./",
    "gallaya": "bldczjfou,nrtsgphaeiqxmwvky';.",
    "yrstmak": "qwfpbjlou;yrstkxnaeivcdgzmh'/.",
    "mayarev": "bldvzqfou,nrtsgyhaeijmcwxkp'/.",
    "ringmak": "fdhmqvwou,stnrzgyaeixkbljpc';.",
    "megamak": "xlywkzfou;crstgbneiajvdmqph/,.",
    "phonkie": "qlmpbzfuoyrnthdcseaijxvk;wg'.,",
    "nrstmak": "qwypbjkou,nrstdlhaeizxcfgvm';.",
    "semimak": "flhvzqwuoysrntkcdeaix'bmjpg,./",
    "sertain": "xldkvzwou;srtnfgyeiaqjmhbpc',.",
    "wreathy": "qgdfvjluo,nsthywreaibcmpkzx/'.",
    "klauser": "k,uypwlmfcoaeidrnthsq.';zxvgbj",
    "gallium": "bldcvzyou,nrtsgfhaeiqxmwjkp';.",
    "colemak": "qwfpgjluy;arstdhneiozxcvbkm,./",
    "rollly2": "youlqkmwp,iaerxgtsnc/\"hjzvdfb.",
    "colemaq": ";wfpbjluyqarstgmneiozxcdkvh/.,",
    "rollmak": "qwfpbzluo;crstgmneaivxydkjh/,.",
    "workman": "qdrwbjfup;ashtgyneoizxmcvkl,./",
    "dvormax": "kyu.?zlmdprieaohnstcx)',(jqfgb",
    "trendei": "klhwbzfou;trndcyseiajmgpqxv',.",
    "hydrogen": "pmldfwcou,ntrhybsaeizqjkxvg';.",
    "vitrimak": "tkvumiajbrwx/fpdgq,sh.'colnzye",
    "nstrtest": "pcdlqzwoy,nstrv.ueiabgmhxkf'j;",
    "whorf-vz": "flhdvzyou,srntmgcaeixjbkqpw';.",
    "mackerel": "qlcgkjfux'arstdyneoizvwmbph/,.",
    "megamak2": "xlcwkzfuo;yrstmbneaiqjgdvph',.",
    "beakl-49": "zyoukgmlpjhieafdstnr/.,'xwcvbq",
    "thallium": "fdhqzjpou,stnrmgcaeivkblxwy';.",
    "sturdy-m": "juofxpclmviean.ydrts,;'hbwgqkz",
    "frontier": "zmuaqpwhlycsieodtnrfvx;'jbg.,k",
    "real-vim": "wchfzqoulymsntd,aerivgbkp.j'x;",
    "zhenvern": "/kdcfqluoyrthsgxneaiwmpbjzv'.,",
    "rollymak": "wqfpbjluo,yrstgmneaivxcdkzh/';",
    "zekykern": "zmcpgqluoyrnstbjheaixfwd;kv/.,",
    "whorfmax": "flhykqwou,srntpcdaeixjbvzmg';.",
    "democrat": "kuiz'qxlpfdemocratnsh;y,.jwgbv",
    "klausler": "k,uypwlmfcoaeidrnthsq.';zxvgbj",
    "rollmak2": "qwypbjlou'crstgmneiazvfdkxh,./",
    "sturgeon": "vmlypqfou.strdgbnaeizkjcwxh';,",
    "ctgap-ev": "wclbvjfou,rsntgyheiaxzmpqkd'./",
    "rollmaky": "qwfpbzluo;crstgmneaiyxvdkjh/,.",
    "klawloid": ",gdhnqruoycstfbwjeai.kmpvlz/'x",
    "colevrak": "blfm;'puoqnrstg,heaixwcdvkyz.j",
    "nstr-sym": "vgdlqzuoybnstr,.aeihpcmw/'kjxf",
    "rsntest1": "qclpkjfou'rsntdyheiazwxbgvm/,.",
    "beakl-19": "q.oujwdnm,haeikgsrtpz'/yxbclfv",
    "hands-up": "fyou,kwclphiea.dtsrnbj'z;vmgxq",
    "arensito": "ql.p';fudkarenbgsitozw,hjvcymx",
    "graphite": "bldwz'foujnrtsgyhaeiqxmcvkp.-/",
    "nitrogen": "pmlcwfdou,ntrsgyhaeizqjbvxk';.",
    "capewell": ".ywdfjpluqaersgbtnioxzcv;kmh,'",
    "beakl-15": "qhouxgcrfzyiea.dstnbj/,k'wmlpv",
    "typehack": "jghpfqvou;rsntkyiaelzwmdbc,'.x",
    "bubbletea": "qchlwpugz'rsntmyaieojxvd;.fb,k",
    "new_londo": "bmlwfq'pujhnrsc.oteikzxgv,ad;y",
    "maplefyre": "kblmv'cuoytsrn.gdeaiqwzhxfp;,j",
    "nstr-apsu": "pgdljkyou'nstrxvheiabcmwqzf,./",
    "vimtastic": "vmncpq.uo,sthdyjreaixkbgfzlw'/",
    "problem-a": "uojmvrxdk,aephblncty.zifwq;sg'",
    "aptv2-ish": "qcdmxzfou/rstlkyneiawgbhvjp',.",
    "canary-gv": "wlypkzfou'crstbxneiaqjgdvmh,./",
    "rsntest2s": "qclmkjfou'rsntdyheiazwxbgvp/,.",
    "beakl-421": "zyou'vglpjhieafdstnrx.,k/wcmbq",
    "tailbound": ".lucvkghyqaresfptnio,z;wjbdmx'",
    "turducken": "yluvkjwob,iretgfsanhzx;dpmcq./",
    "nstr-heia": "bgdlqzyou'nstrkjheiapcmwvxf,./",
    "nrst-test": "xlmgwkpaujnrtsyfhoei/qvczbd.;,",
    "sturdyvim": "vmlcpqfouxstrdy.naeizkjgwbh';,",
    "inqwerted": "trewqpoiuygfdsa;lkjhbvcxz/.,mn",
    "ptbr_nrts": "blmvgjpoy/nrtsdfueiazxqcwkh',.",
    "celestial": ",mdpbqluoycstnfjreaiwgkhvxz'.;",
    "ctgap-2.0": "wcldkjyou/rsthmpneiaqvgfbzx',.",
    "demo-crat": "kyl.qwfnuzdemo,scratpjhi'gbx;v",
    "strontium": "wldvjzkou,srtnmycaeiqxghbpf';.",
    "ctgap-4.0": "xclmkjyou/rsthbpneiaqgwdvzf',.",
    "nitrogen2": "mdlcwfpou,ntrsgyhaeizjxbvkq';.",
    "rollmaky2": "qwfpbzlou;crstgmneiayxvdkjh/,.",
    "ctgap-3.0": "vplcfkuoyjrntsd'aeihzbmgwx,.;q",
    "quick-fox": "thequickbrownfxjmpsvlazydg;,.'",
    "intuition": "bpdl,.wuoycstrqkneaivfgh';mzxj",
    "semiwhorf": "flhdqvwuo,srntkcyeaixjbmzpg;'.",
    "dvorakusp": "/,.pyfgcrlaoeuidhtns;qjkxbmwvz",
    "ruthenium": "wdlfxqbuoyrthsg.neaijkmcvzp',;",
    "crst-apsu": "wlfpbjmuoycrstkxneai'vgdqzh/,.",
    "seht-drai": "fulvb;gnojsehtkqdraiz'mpwycx.,",
    "hieamtsrn": "byou'kdclphiea,mtsrnx().?wgfjz",
    "colemaq-f": ";wgpbjluyqarstfmneiozxcdkvh/.,",
    "hyperroll": "pclmvxuoyfnsrtd.aeihbg'wz/,qjk",
    "republican": "zytdmj,sofrepublicanw;ghk.'vqx",
    "nstr-apsu2": "vgdlqzuoybnstrk,aeihpcmwx/.'jf",
    "radon-test": "fhlgkqyou'snrtbcdaiezmxpvjw,.;",
    "apt26rstag": "wfgdbjluoyrsthkxneaicmp'qzv,./",
    "colemak-kx": "qwfpbjluy'arstgmneiozvcdkxh,./",
    "trendei-ao": "klhwbzfou,trndcysaeijmgpqxv';.",
    "scelestial": "vmdpbqluoysctnfjreaigwkh/xz;,.",
    "minimak-12": "qwdfkyuil;astrghneopzxcvbjm,./",
    "colemak-qi": "qlwmkjfuy'arstgpneiozxcdvbh,./",
    "colemak-dh": "qwfpbjluy;arstgmneiozxcdvkh,./",
    "balance-12": "plcdw'uoyknrstm,aeihzjfgb?.()x",
    "oneproduct": "pldwgjxoyqnrstmuaeihzcfvb,.';k",
    "hands-down": "qchpvkyoj/rsntgwueiaxmldbzf',.",
    "semimak-jq": "flhvz'wuoysrntkcdeaixjbmqpg,./",
    "balance-sfb": "q.umkvfhp,oaetwgsrniz'ydjxclb;",
    "nstrpine-ev": "bcdlwjyou.nstrvpheiaxzgmqkf',;",
    "wobbyphobia": "wcdp.;fuoyrstnvkleaixgmb,'hzqj",
    "engram-apsu": "vwdlqzuoybnsth.,aeicpfmr/'kjxg",
    "apthd-rstag": "xcydbzlou'rsthkjneiavgfpqwm,./",
    "semimak-jqc": "flhvz'wuoysrntkgdeaixjbmqpc,./",
    "nerves-zxcv": "bldmw'foujnrtsgyhaeizxcvqpk.-/",
    "hands-right": "vlcdkz'uoynrstgpheaiqxwmjbf,.;",
    "colemak-dhv": "qwcpbjluy;arstgmneiozxfdkvh/.,",
    "sertain_edit": "vldkqjfou,srtnbycaeizxmhpgw';.",
    "ace-vim-test": "jlhpgqkuo,srncymteaizxbfwvd/;.",
    "trans-rights": "iougpzdlhvyaec'jtrns/.,wfqkmbx",
    "middlephobia": "wcdl;'puoyrsthxzneaivgfm,.bkqj",
    "thumbs-right": "xlcgkz'uoynrstdbheaiqwvmjpf.,;",
    "colemak-qiou": "qlcmkjfoy'arstgpneiuzxwdvbh,./",
    "colemak-dhgm": "qwcpbzluy'arstkjneiovfdgxmh,./",
    "beesechurger": "'lucwkgh,jaresfptniozx;yvbdm.q",
    "sturdy_angle": "vmlcpxfoujstrdy.naeikqgwzbh';,",
    "ruthenium_nl": "wdlcxqpou,rtnsgyhaeizkmbvjf';.",
    "alphabetical": "abcdefghijklmnopqrstuvwxyz.,'/",
    "thallium_rlv": "fdhpvqlou,stncymraeijkbgwzx';.",
    "amini-layout": "yoxclibfud;p',smgnjeahqtrkzwv.",
    "colemak-pine": "qlcgkjfuy/arstdbneiozxwmvph',.",
    "beakl-19-bis": "qyouzwdnckhiea,gtrspj'/.xvmlfb",
    "colemak-qi;x": ";lcmkjfuyqarstgpneiozxwdvbh/.,",
    "aptbomination": "qwfpbzluoyrsthkjneaixcgdv;m,.'",
    "bleating_goat": "juoq;kdclwiean'mhstr.,pyxbfgvz",
    "rolls-but-alt": "rxdtgq,oihwncmkuaz;fblsyv'.ejp",
    "stronglytyped": "bzlfgjkou,nrtswyheiaxqmcvpd'.;",
    "layoutissimus": "pqmhxy,ojznctsl.uaiekbfrdvgw'/",
    "recycling_bin": "juoq;vdclkiean'mhsrt.,pyxbfgwz",
    "gallaya_angle": "bldcqjfou,nrtsgphaeixmwvzky';.",
    "whorfmax-ortho": "flhyzqwou,srntpcdaeixjbvkmg';.",
    "vitrimak-ortho": "e.viacoqytsj/dgmpx,wrk'lnfuzbh",
    "hands-down-neu": "wfmpv/.q\"'rsntb,aeihxcldg-uoyk",
    "rsi-terminated": "zcywkxlu,qrsitgmneaojfpdbvh'.?",
    "whorf_but_based": "vlhdqjwou,srntgycaeizxbmkpf';.",
    "deformed-turkey": "qwdpzjluo,rstcymneaixbkgfvh;'.",
    "capewell-dvorak": "',.pyqfgrkoaeiudhtnszxcvjlmwb;",
    "colemak-dhgm-ortho": "qwcpkjluy'arstgmneiozvfdbxh,./",
    "adnw-english-bigram": "qyu.?zmldbsieaohnrtcj)',(fxwkv",
    "hands-down-reference": "qchpvkyoj/rsntgwueiaxmldbzf',."
}